name: flutter_base_page
description: 项目页面和视图的基类.
version: 0.0.1
repository: https://github.com/dvlproad/001-UIKit-CQDemo-Flutter/tree/master/flutter_base_page
homepage: https://github.com/dvlproad/001-UIKit-CQDemo-Flutter/tree/master/flutter_base_page

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lifecycle_kit: ^0.0.1
    # path: ../flutter_lifecycle_kit/

  flutter_theme_helper: ^0.0.1

  visibility_detector: ^0.4.0+2
  # cached_network_image: any
  # flutter_theme_helper: #^0.1.0
  #   path: ../flutter_theme_helper/
  flutter_error_catch: ^0.0.1
  #   path: ../flutter_error_catch/

  flutter_baseui_kit: ^0.0.2     # 为了引入 ThemeBorderButton
  #   path: ../flutter_baseui_kit/ 

  flutter_overlay_kit: ^0.0.2
  #   # path: ../flutter_overlay_kit/

  flutter_effect_kit: ^0.0.1
  #   path: ../flutter_effect_kit/

  flutter_log_with_env: ^0.0.2

  flutter_buried_point: ^0.0.1
  #   path: ../flutter_buried_point/

  flutter_optimize_interacte: ^0.0.1

  flutter_network_base: ^0.0.1
  
  #   path: ../flutter_network_base/
  # app_gated_launch:
  #   path: ../app_gated_launch/
  # app_common:
  #   path: ../app_common/
  # app_page_load:
  #   path: ../app_page_load/

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/
  - assets/empty/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
